name: Run Snippets Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-snippets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: create env file
        run: |
          touch .env
          echo FERN_API_KEY=${{ secrets.FERN_API_KEY }} >> .env

      - name: Run snippets.js
        run: node snippets.js
