name: Run Snippets Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-snippets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Run snippets.js
        run: node snippets.js

      - name: Upload OpenAPI specs
        uses: actions/upload-artifact@v2
        with:
          name: openapi
          path: openapi.json
